// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CheckTodayAffirmation(arg1) {
  return window['go']['backend']['App']['CheckTodayAffirmation'](arg1);
}

export function GetActiveAffirmation() {
  return window['go']['backend']['App']['GetActiveAffirmation']();
}

export function GetAffirmationStreak() {
  return window['go']['backend']['App']['GetAffirmationStreak']();
}

export function GetAnswer(arg1) {
  return window['go']['backend']['App']['GetAnswer'](arg1);
}

export function GetDailyQuestion() {
  return window['go']['backend']['App']['GetDailyQuestion']();
}

export function LogAffirmation(arg1) {
  return window['go']['backend']['App']['LogAffirmation'](arg1);
}

export function SaveAffirmation(arg1) {
  return window['go']['backend']['App']['SaveAffirmation'](arg1);
}

export function SaveAnswer(arg1, arg2) {
  return window['go']['backend']['App']['SaveAnswer'](arg1, arg2);
}
