// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CheckTodayAffirmation(arg1) {
  return window['go']['backend']['App']['CheckTodayAffirmation'](arg1);
}

export function CreateNewAnswer(arg1, arg2) {
  return window['go']['backend']['App']['CreateNewAnswer'](arg1, arg2);
}

export function DeleteAffirmation(arg1) {
  return window['go']['backend']['App']['DeleteAffirmation'](arg1);
}

export function DeleteAffirmationLog(arg1) {
  return window['go']['backend']['App']['DeleteAffirmationLog'](arg1);
}

export function DeleteAnswer(arg1) {
  return window['go']['backend']['App']['DeleteAnswer'](arg1);
}

export function DeleteQuestion(arg1) {
  return window['go']['backend']['App']['DeleteQuestion'](arg1);
}

export function GetActiveAffirmation() {
  return window['go']['backend']['App']['GetActiveAffirmation']();
}

export function GetAffirmationStreak() {
  return window['go']['backend']['App']['GetAffirmationStreak']();
}

export function GetAllAffirmationLogs() {
  return window['go']['backend']['App']['GetAllAffirmationLogs']();
}

export function GetAllAffirmations() {
  return window['go']['backend']['App']['GetAllAffirmations']();
}

export function GetAllAnswers() {
  return window['go']['backend']['App']['GetAllAnswers']();
}

export function GetAllQuestions() {
  return window['go']['backend']['App']['GetAllQuestions']();
}

export function GetAnswerHistoryByQuestionID(arg1) {
  return window['go']['backend']['App']['GetAnswerHistoryByQuestionID'](arg1);
}

export function GetAnswersByDate(arg1) {
  return window['go']['backend']['App']['GetAnswersByDate'](arg1);
}

export function GetQuestionById(arg1) {
  return window['go']['backend']['App']['GetQuestionById'](arg1);
}

export function GetRandomQuestion() {
  return window['go']['backend']['App']['GetRandomQuestion']();
}

export function GetTodayDateStr() {
  return window['go']['backend']['App']['GetTodayDateStr']();
}

export function GetTodaysAnswer() {
  return window['go']['backend']['App']['GetTodaysAnswer']();
}

export function GetTodaysAnsweredQuestion() {
  return window['go']['backend']['App']['GetTodaysAnsweredQuestion']();
}

export function LogAffirmation(arg1) {
  return window['go']['backend']['App']['LogAffirmation'](arg1);
}

export function SaveAffirmation(arg1) {
  return window['go']['backend']['App']['SaveAffirmation'](arg1);
}

export function UpdateAffirmation(arg1, arg2) {
  return window['go']['backend']['App']['UpdateAffirmation'](arg1, arg2);
}

export function UpdateAnswer(arg1, arg2) {
  return window['go']['backend']['App']['UpdateAnswer'](arg1, arg2);
}

export function UpdateQuestion(arg1, arg2) {
  return window['go']['backend']['App']['UpdateQuestion'](arg1, arg2);
}
