// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {models} from '../models';

export function CheckTodayAffirmation(arg1:number):Promise<boolean>;

export function GetActiveAffirmation():Promise<models.Affirmation>;

export function GetAffirmationStreak():Promise<number>;

export function GetAnswer(arg1:number):Promise<models.Answer>;

export function GetDailyQuestion():Promise<models.Question>;

export function LogAffirmation(arg1:number):Promise<void>;

export function SaveAffirmation(arg1:string):Promise<models.Affirmation>;

export function SaveAnswer(arg1:number,arg2:string):Promise<models.Answer>;
