// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddGratitudeItem(arg1) {
  return window['go']['backend']['App']['AddGratitudeItem'](arg1);
}

export function AddQuestion(arg1) {
  return window['go']['backend']['App']['AddQuestion'](arg1);
}

export function CheckTodayAffirmation(arg1) {
  return window['go']['backend']['App']['CheckTodayAffirmation'](arg1);
}

export function CountTodayGratitudeEntries() {
  return window['go']['backend']['App']['CountTodayGratitudeEntries']();
}

export function CreateNewAnswer(arg1, arg2) {
  return window['go']['backend']['App']['CreateNewAnswer'](arg1, arg2);
}

export function DeleteAffirmation(arg1) {
  return window['go']['backend']['App']['DeleteAffirmation'](arg1);
}

export function DeleteAffirmationLog(arg1) {
  return window['go']['backend']['App']['DeleteAffirmationLog'](arg1);
}

export function DeleteAnswer(arg1) {
  return window['go']['backend']['App']['DeleteAnswer'](arg1);
}

export function DeleteGratitudeItem(arg1) {
  return window['go']['backend']['App']['DeleteGratitudeItem'](arg1);
}

export function DeleteQuestion(arg1) {
  return window['go']['backend']['App']['DeleteQuestion'](arg1);
}

export function GetActiveAffirmation() {
  return window['go']['backend']['App']['GetActiveAffirmation']();
}

export function GetAffirmationStreak() {
  return window['go']['backend']['App']['GetAffirmationStreak']();
}

export function GetAllAffirmationLogs() {
  return window['go']['backend']['App']['GetAllAffirmationLogs']();
}

export function GetAllAffirmations() {
  return window['go']['backend']['App']['GetAllAffirmations']();
}

export function GetAllAnswers() {
  return window['go']['backend']['App']['GetAllAnswers']();
}

export function GetAllGratitudeEntries() {
  return window['go']['backend']['App']['GetAllGratitudeEntries']();
}

export function GetAllQuestions() {
  return window['go']['backend']['App']['GetAllQuestions']();
}

export function GetAnswerHistoryByQuestionID(arg1) {
  return window['go']['backend']['App']['GetAnswerHistoryByQuestionID'](arg1);
}

export function GetGratitudeItemsByDate(arg1) {
  return window['go']['backend']['App']['GetGratitudeItemsByDate'](arg1);
}

export function GetGratitudeStreak() {
  return window['go']['backend']['App']['GetGratitudeStreak']();
}

export function GetLastNDaysWithGratitude(arg1) {
  return window['go']['backend']['App']['GetLastNDaysWithGratitude'](arg1);
}

export function GetQuestionById(arg1) {
  return window['go']['backend']['App']['GetQuestionById'](arg1);
}

export function GetRandomQuestion() {
  return window['go']['backend']['App']['GetRandomQuestion']();
}

export function GetRecentAnswers(arg1) {
  return window['go']['backend']['App']['GetRecentAnswers'](arg1);
}

export function GetTodayGratitudeItems() {
  return window['go']['backend']['App']['GetTodayGratitudeItems']();
}

export function HasTodayGratitudeEntries() {
  return window['go']['backend']['App']['HasTodayGratitudeEntries']();
}

export function LogAffirmation(arg1) {
  return window['go']['backend']['App']['LogAffirmation'](arg1);
}

export function SaveAffirmation(arg1) {
  return window['go']['backend']['App']['SaveAffirmation'](arg1);
}

export function UpdateAffirmation(arg1, arg2) {
  return window['go']['backend']['App']['UpdateAffirmation'](arg1, arg2);
}

export function UpdateAnswer(arg1, arg2) {
  return window['go']['backend']['App']['UpdateAnswer'](arg1, arg2);
}

export function UpdateGratitudeItem(arg1, arg2) {
  return window['go']['backend']['App']['UpdateGratitudeItem'](arg1, arg2);
}

export function UpdateQuestion(arg1, arg2) {
  return window['go']['backend']['App']['UpdateQuestion'](arg1, arg2);
}
