export const CREATIVITY_PROMPTS = [
  "Bicycle",
  "Moonlight",
  "Coffee cup",
  "Autumn leaves",
  "Old keys",
  "Ocean waves",
  "Grandfather clock",
  "Paper airplane",
  "Broken mirror",
  "Fresh bread",
  "Sunset",
  "Chess piece",
  "Empty theater",
  "Candle flame",
  "Vintage camera",
  "Train whistle",
  "Spider web",
  "Lost button",
  "City skyline",
  "Wooden bridge",
  "Echo",
  "Bird's nest",
  "Worn book",
  "Footprints in snow",
  "Telescope",
  "Wrapped gift",
  "Origami crane",
  "Seashell",
  "Hourglass",
  "Kaleidoscope",
  "Chocolate",
  "Lightning",
  "Vinyl record",
  "Compass",
  "Umbrella",
  "Puzzle piece",
  "Kite",
  "Feather",
  "Abandoned house",
  "Guitar string",
  "Masquerade mask",
  "Dandelion",
  "Cracked pavement",
  "Magnifying glass",
  "Castle",
  "Train ticket",
  "Fingerprint",
  "Whisper",
  "Doorknob",
  "Sandcastle",
  "Lantern",
  "Typewriter",
  "Quilt",
  "Music box",
  "Foggy morning",
  "Anchor",
  "Stained glass",
  "Teacup",
  "Silver lining",
  "Rusty key",
  "Lighthouse",
  "Bookshelf",
  "Window frost",
  "Pocket watch",
  "Treasure map",
  "Wind chimes",
  "Carousel",
  "Smoke signal",
  "Chessboard",
  "Piano keys",
  "Shooting star",
  "Rowboat",
  "Antique shop",
  "Snowflake",
  "Inkwell",
  "Dream catcher",
  "Butterfly effect",
  "Chandelier",
  "Horoscope",
  "Magnolia tree",
  "Reflection",
  "Thunderstorm",
  "Campfire",
  "Spiral staircase",
  "Perfume bottle",
  "Secret passage",
  "Constellation",
  "Mosaic",
  "Scarecrow",
  "Hot air balloon",
  "Anthill",
  "Echo chamber",
  "Fountain pen",
  "First snowfall",
  "Crystal ball",
  "Library card",
  "Handwritten letter",
  "Hammock",
  "Waterfall",
  "Skeleton key",
  "Brass doorbell",
  "Labyrinth",
  "Last page",
  "Weathervane",
  "Sundial",
  "Jigsaw puzzle",
  "Stopwatch",
  "Windmill",
  "Penny in a fountain",
  "Stone wall",
  "Telescope",
  "First light",
  "Envelope",
  "Chameleon",
  "Pinwheel",
  "Tin can telephone",
  "Robin's egg",
  "Origami boat",
  "Raindrops on leaves",
  "Mirage",
  "Kaleidoscope",
  "Phonograph",
  "Fireflies",
  "Tidal pool",
  "Cobblestone street",
  "Needle and thread",
  "Driftwood",
  "Shadow puppets",
  "Ivy wall",
  "Ferris wheel",
  "Family recipe",
  "Handprint",
  "Broken string",
  "Meteor shower",
  "Dusty attic",
  "Harmony",
  "Raindrop",
  "Time capsule",
  "Pocket map",
  "Confetti",
  "Fallen leaf",
  "Periscope",
  "Underground passage",
  "Domino effect",
  "Root cellar",
  "North star",
  "Canoe",
  "Tarnished silver",
  "Silhouette",
  "Crow's nest",
  "Dandelion seeds",
  "Fingerprint",
  "Pocket knife",
  "Brass instrument",
  "Forgotten book",
  "Ripple",
  "Circus tent",
  "Morning dew",
  "Rope swing",
  "Amber",
  "Bamboo forest",
  "Conch shell",
  "Maple syrup",
  "Wishing well",
  "Clay pot",
  "Abandoned railway",
  "Silk scarf",
  "Chalk drawing",
  "Misty valley",
  "Sandpaper",
  "Tumbleweed",
  "Charcoal sketch",
  "Coral reef",
  "Lavender",
  "Fox den",
  "Wooden spoon",
  "Astrolabe",
  "Dewdrop",
  "Wax seal",
  "Spinning top",
  "Woven basket",
  "Barn raising",
  "Pinecone",
  "Sundial",
  "Spider silk",
  "Gargoyle",
  "Thimble",
  "Map legend",
  "Waxing moon",
  "Birdsong",
  "Wheat field",
  "Palm reading",
  "Dappled light",
  "Rusty hinge",
  "Fountain",
  "Thistle",
  "Sand dollar",
  "Wishbone",
  "Lodestone",
  "Pomegranate",
  "Hollowed tree",
  "Pressed flower",
  "Gnarled root",
  "Bird migration",
  "Hibernation",
  "Solstice",
  "Highland mist",
  "Salt crystal",
  "Empty birdcage",
  "Copper penny",
  "Cinnamon stick",
  "Bronze statue",
  "Doorway",
  "Wooden bridge",
  "Yarn skein",
  "Hedge maze",
  "Ember",
  "Crow's feather",
  "Linen handkerchief",
  "Soapstone",
  "Nautilus shell",
  "Old growth forest",
  "Storm clouds",
  "Brass bell",
  "Fossil",
  "Amber resin",
  "Pinhole camera",
  "Quill pen",
  "Barnacle",
  "Desert mirage",
  "Ribbon",
  "Clay pot",
  "Paper lantern",
  "Milkweed pod",
  "Knitting needle",
  "Cattail",
  "Lichen",
  "Sundial",
  "Terracotta",
  "Spindle",
  "Stump",
  "Chimney smoke",
  "Geode",
  "Tide pool",
  "Moss-covered stone",
  "Hollyhock",
  "Honeycomb",
  "Thatched roof",
  "Arrowhead",
  "Morel mushroom",
  "Brass key",
  "Wax seal",
  "Copper pot",
  "Magnolia blossom",
  "Weathered fence",
  "Shipwreck",
  "Loom",
  "Butterfly wing",
  "Glass float",
  "Cedar chest",
  "Antler",
  "Willow tree",
  "Tallow candle",
  "Rusted bucket",
  "Water wheel",
  "Sundial",
  "Alchemy",
  "Sextant",
  "Mason jar",
  "Almanac",
  "Tree ring",
  "Opal",
  "Abacus",
  "Mist on water",
  "Cuckoo clock",
  "Seed packet",
  "Soapstone",
  "Sheet music",
  "Honey dipper",
  "Astrolabe",
  "Garden gate",
  "Root cellar",
  "Tintype photograph",
  "Arrow fletching",
  "Leather-bound book",
  "Fish scale",
  "Beehive",
  "Pewter mug",
  "Thimble",
  "Copper wire",
  "Inkwell",
  "Stone arch",
  "Sundial",
  "Morning glory",
  "Hearth",
  "Locket",
  "Candlestick",
  "Harvest moon",
  "Flint",
  "Iron kettle",
  "Doorway",
  "Quartz crystal",
  "Tapestry",
  "Millstone",
  "Pitcher pump",
  "Wooden bucket",
  "Crow's nest",
  "Smoke signal",
  "Cobweb",
  "Sundial",
  "Tarnished silver",
  "Spinning wheel",
  "Skeleton key",
  "Mantle clock",
  "Burlap sack",
  "Briar patch",
  "Thyme",
  "Iron gate",
  "Quill",
  "Waterwheel",
  "Tanner's bench",
  "Copper penny",
  "Library ladder",
  "Orchard",
  "Rolling pin",
  "Window box",
  "Bellows",
  "Weathered oak",
  "Woodpecker",
  "Hearthstone",
  "Cider press",
  "Barometer",
  "Butter churn",
  "Rooster weather vane",
  "Barn door",
  "Pickle jar",
  "Root cellar",
  "Handloom",
  "Wrought iron",
  "Bread oven",
  "Tincture bottle",
  "Horseshoe",
  "Wicker basket",
  "Sundial",
  "Inkwell",
  "Rope swing",
  "Watering can",
  "Spyglass",
  "Washboard",
  "Leather strop",
  "Spectacles",
  "Hurricane lamp",
  "Whetstone",
  "Cobbler's bench",
  "Whalebone",
  "Drying herbs",
  "Shepherd's crook",
  "Copper gutters",
  "Butter mold",
  "Doorstop",
  "Clothespin",
  "Wheelbarrow",
  "Iron doorstop",
  "Garden trowel",
  "Amber",
];
